export const words: COMMON.Word[] = [
    {"word": "I", "translation": "я", "levels": ["pronoun"]},
    {"word": "you", "translation": "ты, вы", "levels": ["pronoun", "A1"]},
    {"word": "he", "translation": "он", "levels": ["pronoun", "A1"]},
    {"word": "she", "translation": "она", "levels": ["pronoun", "A1"]},
    {"word": "it", "translation": "оно", "levels": ["pronoun", "A1"]},
    {"word": "we", "translation": "мы", "levels": ["pronoun", "A1"]},
    {"word": "they", "translation": "они", "levels": ["pronoun", "A1"]},
    {"word": "me", "translation": "меня", "levels": ["pronoun", "A1"]},
    {"word": "him", "translation": "его", "levels": ["pronoun", "A1"]},
    {"word": "her", "translation": "её", "levels": ["pronoun", "A1"]},
    {"word": "us", "translation": "нас", "levels": ["pronoun", "A1"]},
    {"word": "them", "translation": "их", "levels": ["pronoun", "A1"]},
    {"word": "my", "translation": "мой", "levels": ["pronoun", "A1"]},
    {"word": "your", "translation": "твой, ваш", "levels": ["pronoun", "A1"]},
    {"word": "his", "translation": "его", "levels": ["pronoun", "A1"]},
    {"word": "her", "translation": "её", "levels": ["pronoun", "A1"]},
    {"word": "its", "translation": "его", "levels": ["pronoun", "A1"]},
    {"word": "our", "translation": "наш", "levels": ["pronoun", "A1"]},
    {"word": "their", "translation": "их", "levels": ["pronoun", "A1"]},
    {"word": "this", "translation": "этот", "levels": ["pronoun", "A1"]},
    {"word": "that", "translation": "тот", "levels": ["pronoun", "A1"]},
    {"word": "these", "translation": "эти", "levels": ["pronoun", "A1"]},
    {"word": "those", "translation": "те", "levels": ["pronoun", "A1"]},
    {"word": "who", "translation": "кто", "levels": ["pronoun", "A2"]},
    {"word": "what", "translation": "что", "levels": ["pronoun", "A2"]},
    {"word": "which", "translation": "который", "levels": ["pronoun", "A2"]},
    {"word": "whom", "translation": "кого", "levels": ["pronoun", "A2"]},
    {"word": "someone", "translation": "кто-то", "levels": ["pronoun", "A2"]},
    {"word": "somebody", "translation": "кто-то", "levels": ["pronoun", "A2"]},
    {"word": "something", "translation": "что-то", "levels": ["pronoun", "A2"]},
    {"word": "anyone", "translation": "кто угодно", "levels": ["pronoun", "A2"]},
    {"word": "anybody", "translation": "кто угодно", "levels": ["pronoun", "A2"]},
    {"word": "anything", "translation": "что угодно", "levels": ["pronoun", "A2"]},
    {"word": "nobody", "translation": "никто", "levels": ["pronoun", "A2"]},
    {"word": "nothing", "translation": "ничто", "levels": ["pronoun", "A2"]},
    {"word": "hello", "translation": "привет", "levels": ["required-100"]},
    {"word": "goodbye", "translation": "до свидания", "levels": ["A1", "required-100"]},
    {"word": "please", "translation": "пожалуйста", "levels": ["A1", "required-100"]},
    {"word": "thank you", "translation": "спасибо", "levels": ["A1", "required-100"]},
    {"word": "sorry", "translation": "извините", "levels": ["required-100"]},
    {"word": "yes", "translation": "да", "levels": ["A1", "required-100"]},
    {"word": "no", "translation": "нет", "levels": ["A1", "required-100"]},
    {"word": "apple", "translation": "яблоко", "levels": ["A1"]},
    {"word": "book", "translation": "книга", "levels": ["A1"]},
    {"word": "cat", "translation": "кот", "levels": ["A1"]},
    {"word": "dog", "translation": "собака", "levels": ["A1"]},
    {"word": "egg", "translation": "яйцо", "levels": ["A1"]},
    {"word": "fish", "translation": "рыба", "levels": ["A1"]},
    {"word": "grape", "translation": "виноград", "levels": ["A1"]},
    {"word": "house", "translation": "дом", "levels": ["A1", "required-100"]},
    {"word": "ice", "translation": "лед", "levels": ["A1"]},
    {"word": "juice", "translation": "сок", "levels": ["A1"]},
    {"word": "key", "translation": "ключ", "levels": ["A1"]},
    {"word": "lamp", "translation": "лампа", "levels": ["A1"]},
    {"word": "man", "translation": "мужчина", "levels": ["A1", "required-100"]},
    {"word": "night", "translation": "ночь", "levels": ["A1", "required-100"]},
    {"word": "orange", "translation": "апельсин", "levels": ["A1"]},
    {"word": "pen", "translation": "ручка", "levels": ["A1"]},
    {"word": "queen", "translation": "королева", "levels": ["A1"]},
    {"word": "rain", "translation": "дождь", "levels": ["A1", "required-100"]},
    {"word": "sun", "translation": "солнце", "levels": ["A1", "required-100"]},
    {"word": "table", "translation": "стол", "levels": ["A1", "required-100"]},
    {"word": "umbrella", "translation": "зонт", "levels": ["A1"]},
    {"word": "van", "translation": "фургон", "levels": ["A1"]},
    {"word": "water", "translation": "вода", "levels": ["A1", "required-100"]},
    {"word": "x-ray", "translation": "рентген", "levels": ["A1"]},
    {"word": "yellow", "translation": "жёлтый", "levels": ["A1"]},
    {"word": "zebra", "translation": "зебра", "levels": ["A1"]},
    {"word": "animal", "translation": "животное", "levels": ["A1"]},
    {"word": "ball", "translation": "мяч", "levels": ["A1"]},
    {"word": "car", "translation": "машина", "levels": ["A1", "required-100"]},
    {"word": "door", "translation": "дверь", "levels": ["A1", "required-100"]},
    {"word": "ear", "translation": "ухо", "levels": ["A1"]},
    {"word": "flower", "translation": "цветок", "levels": ["A1"]},
    {"word": "grass", "translation": "трава", "levels": ["A1"]},
    {"word": "hat", "translation": "шляпа", "levels": ["A1"]},
    {"word": "ice-cream", "translation": "мороженое", "levels": ["A1"]},
    {"word": "juice", "translation": "сок", "levels": ["A1"]},
    {"word": "key", "translation": "ключ", "levels": ["A1"]},
    {"word": "leaf", "translation": "лист", "levels": ["A1"]},
    {"word": "moon", "translation": "луна", "levels": ["A1"]},
    {"word": "net", "translation": "сеть", "levels": ["A1"]},
    {"word": "orange", "translation": "апельсин", "levels": ["A1"]},
    {"word": "pig", "translation": "свинья", "levels": ["A1"]},
    {"word": "queen", "translation": "королева", "levels": ["A1"]},
    {"word": "river", "translation": "река", "levels": ["A1"]},
    {"word": "star", "translation": "звезда", "levels": ["A1"]},
    {"word": "tea", "translation": "чай", "levels": ["A1"]},
    {"word": "umbrella", "translation": "зонт", "levels": ["A1"]},
    {"word": "vase", "translation": "ваза", "levels": ["A1"]},
    {"word": "wind", "translation": "ветер", "levels": ["A1", "required-100"]},
    {"word": "yawn", "translation": "зевать", "levels": ["A1"]},
    {"word": "zoo", "translation": "зоопарк", "levels": ["A1"]},
    {"word": "airplane", "translation": "самолёт", "levels": ["A1"]},
    {"word": "bag", "translation": "сумка", "levels": ["A1"]},
    {"word": "cake", "translation": "торт", "levels": ["A1"]},
    {"word": "drink", "translation": "напиток", "levels": ["A1"]},
    {"word": "eggplant", "translation": "баклажан", "levels": ["A1"]},
    {"word": "flower", "translation": "цветок", "levels": ["A1"]},
    {"word": "girl", "translation": "девочка", "levels": ["A1"]},
    {"word": "hot", "translation": "горячий", "levels": ["A1"]},
    {"word": "ice", "translation": "лед", "levels": ["A1"]},
    {"word": "juice", "translation": "сок", "levels": ["A1"]},
    {"word": "key", "translation": "ключ", "levels": ["A1"]},
    {"word": "lamp", "translation": "лампа", "levels": ["A1"]},
    {"word": "milk", "translation": "молоко", "levels": ["A1"]},
    {"word": "nose", "translation": "нос", "levels": ["A1"]},
    {"word": "orange", "translation": "апельсин", "levels": ["A1"]},
    {"word": "pen", "translation": "ручка", "levels": ["A1"]},
    {"word": "queen", "translation": "королева", "levels": ["A1"]},
    {"word": "school", "translation": "школа", "levels": ["A1", "required-100"]},
    {"word": "tooth", "translation": "зуб", "levels": ["A1"]},
    {"word": "umbrella", "translation": "зонт", "levels": ["A1"]},
    {"word": "village", "translation": "деревня", "levels": ["A1"]},
    {"word": "window", "translation": "окно", "levels": ["A1", "required-100"]},
    {"word": "yogurt", "translation": "йогурт", "levels": ["A1"]},
    {"word": "zebra", "translation": "зебра", "levels": ["A1"]},
    {"word": "beach", "translation": "пляж", "levels": ["A1"]},
    {"word": "computer", "translation": "компьютер", "levels": ["A1"]},
    {"word": "dog", "translation": "собака", "levels": ["A1"]},
    {"word": "egg", "translation": "яйцо", "levels": ["A1"]},
    {"word": "food", "translation": "еда", "levels": ["A1", "required-100"]},
    {"word": "grape", "translation": "виноград", "levels": ["A1"]},
    {"word": "hat", "translation": "шляпа", "levels": ["A1"]},
    {"word": "ice-cream", "translation": "мороженое", "levels": ["A1"]},
    {"word": "juice", "translation": "сок", "levels": ["A1"]},
    {"word": "kiwi", "translation": "киви", "levels": ["A1"]},
    {"word": "lemon", "translation": "лимон", "levels": ["A1"]},
    {"word": "milk", "translation": "молоко", "levels": ["A1"]},
    {"word": "notebook", "translation": "блокнот", "levels": ["A1"]},
    {"word": "orange", "translation": "апельсин", "levels": ["A1"]},
    {"word": "pear", "translation": "груша", "levels": ["A1"]},
    {"word": "rabbit", "translation": "кролик", "levels": ["A1"]},
    {"word": "star", "translation": "звезда", "levels": ["A1"]},
    {"word": "train", "translation": "поезд", "levels": ["A1", "required-100"]},
    {"word": "umbrella", "translation": "зонт", "levels": ["A1"]},
    {"word": "violin", "translation": "скрипка", "levels": ["A1"]},
    {"word": "wolf", "translation": "волк", "levels": ["A1"]},
    {"word": "yawn", "translation": "зевать", "levels": ["A1"]},
    {"word": "zoo", "translation": "зоопарк", "levels": ["A1"]},
    {"word": "airport", "translation": "аэропорт", "levels": ["A2"]},
    {"word": "bicycle", "translation": "велосипед", "levels": ["A2"]},
    {"word": "city", "translation": "город", "levels": ["A2"]},
    {"word": "dance", "translation": "танец", "levels": ["A2"]},
    {"word": "engine", "translation": "двигатель", "levels": ["A2"]},
    {"word": "forest", "translation": "лес", "levels": ["A2"]},
    {"word": "guitar", "translation": "гитара", "levels": ["A2"]},
    {"word": "hotel", "translation": "отель", "levels": ["A2"]},
    {"word": "island", "translation": "остров", "levels": ["A2"]},
    {"word": "jacket", "translation": "куртка", "levels": ["A2"]},
    {"word": "kitchen", "translation": "кухня", "levels": ["A2"]},
    {"word": "library", "translation": "библиотека", "levels": ["A2"]},
    {"word": "movie", "translation": "фильм", "levels": ["A2"]},
    {"word": "news", "translation": "новости", "levels": ["A2"]},
    {"word": "office", "translation": "офис", "levels": ["A2"]},
    {"word": "park", "translation": "парк", "levels": ["A2"]},
    {"word": "question", "translation": "вопрос", "levels": ["A2", "required-100"]},
    {"word": "restaurant", "translation": "ресторан", "levels": ["A2"]},
    {"word": "school", "translation": "школа", "levels": ["A2"]},
    {"word": "uniform", "translation": "форма", "levels": ["A2"]},
    {"word": "village", "translation": "деревня", "levels": ["A2"]},
    {"word": "website", "translation": "веб-сайт", "levels": ["A2"]},
    {"word": "youth", "translation": "молодёжь", "levels": ["A2"]},
    {"word": "zoo", "translation": "зоопарк", "levels": ["A2"]},
    {"word": "advice", "translation": "совет", "levels": ["A2"]},
    {"word": "bottle", "translation": "бутылка", "levels": ["A2"]},
    {"word": "camera", "translation": "камера", "levels": ["A2"]},
    {"word": "doctor", "translation": "врач", "levels": ["A2", "required-100"]},
    {"word": "envelope", "translation": "конверт", "levels": ["A2"]},
    {"word": "fruit", "translation": "фрукт", "levels": ["A2"]},
    {"word": "glove", "translation": "перчатка", "levels": ["A2"]},
    {"word": "homework", "translation": "домашнее задание", "levels": ["A2", "required-100"]},
    {"word": "internet", "translation": "интернет", "levels": ["A2"]},
    {"word": "juice", "translation": "сок", "levels": ["A2"]},
    {"word": "kitchen", "translation": "кухня", "levels": ["A2"]},
    {"word": "library", "translation": "библиотека", "levels": ["A2"]},
    {"word": "movie", "translation": "фильм", "levels": ["A2"]},
    {"word": "notebook", "translation": "блокнот", "levels": ["A2"]},
    {"word": "ocean", "translation": "океан", "levels": ["A2"]},
    {"word": "passport", "translation": "паспорт", "levels": ["A2"]},
    {"word": "refrigerator", "translation": "холодильник", "levels": ["A2"]},
    {"word": "sandwich", "translation": "бутерброд", "levels": ["A2"]},
    {"word": "toothbrush", "translation": "зубная щётка", "levels": ["A2"]},
    {"word": "umbrella", "translation": "зонт", "levels": ["A2"]},
    {"word": "vacation", "translation": "отпуск", "levels": ["A2"]},
    {"word": "wallet", "translation": "кошелёк", "levels": ["A2"]},
    {"word": "yogurt", "translation": "йогурт", "levels": ["A2"]},
    {"word": "zebra", "translation": "зебра", "levels": ["A2"]},
    {"word": "airline", "translation": "авиакомпания", "levels": ["A2"]},
    {"word": "baker", "translation": "пекарь", "levels": ["A2"]},
    {"word": "camera", "translation": "камера", "levels": ["A2"]},
    {"word": "dinner", "translation": "ужин", "levels": ["A2"]},
    {"word": "engine", "translation": "двигатель", "levels": ["A2"]},
    {"word": "furniture", "translation": "мебель", "levels": ["A2"]},
    {"word": "gym", "translation": "тренажёрный зал", "levels": ["A2"]},
    {"word": "hotel", "translation": "отель", "levels": ["A2"]},
    {"word": "island", "translation": "остров", "levels": ["A2"]},
    {"word": "jacket", "translation": "куртка", "levels": ["A2"]},
    {"word": "kitchen", "translation": "кухня", "levels": ["A2"]},
    {"word": "library", "translation": "библиотека", "levels": ["A2"]},
    {"word": "music", "translation": "музыка", "levels": ["A2"]},
    {"word": "news", "translation": "новости", "levels": ["A2"]},
    {"word": "orange", "translation": "апельсин", "levels": ["A2"]},
    {"word": "photograph", "translation": "фотография", "levels": ["A2"]},
    {"word": "quiz", "translation": "викторина", "levels": ["A2"]},
    {"word": "radio", "translation": "радио", "levels": ["A2"]},
    {"word": "station", "translation": "станция", "levels": ["A2"]},
    {"word": "phone", "translation": "телефон", "levels": ["A2", "required-100"]},
    {"word": "university", "translation": "университет", "levels": ["A2"]},
    {"word": "vacation", "translation": "отпуск", "levels": ["A2"]},
    {"word": "weekend", "translation": "выходные", "levels": ["A2"]},
    {"word": "yawn", "translation": "зевать", "levels": ["A2"]},
    {"word": "zoo", "translation": "зоопарк", "levels": ["A2"]},
    {"word": "accomplish", "translation": "достигать", "levels": ["B1"]},
    {"word": "advantage", "translation": "преимущество", "levels": ["B1"]},
    {"word": "advice", "translation": "совет", "levels": ["B1"]},
    {"word": "affect", "translation": "влиять", "levels": ["B1"]},
    {"word": "agreement", "translation": "соглашение", "levels": ["B1"]},
    {"word": "amazing", "translation": "удивительный", "levels": ["B1"]},
    {"word": "ambition", "translation": "амбиция", "levels": ["B1"]},
    {"word": "annoying", "translation": "раздражающий", "levels": ["B1"]},
    {"word": "anxiety", "translation": "тревога", "levels": ["B1"]},
    {"word": "appointment", "translation": "назначение", "levels": ["B1"]},
    {"word": "appreciate", "translation": "ценить", "levels": ["B1"]},
    {"word": "argument", "translation": "спор", "levels": ["B1"]},
    {"word": "arrangement", "translation": "договоренность", "levels": ["B1"]},
    {"word": "attempt", "translation": "попытка", "levels": ["B1"]},
    {"word": "average", "translation": "средний", "levels": ["B1"]},
    {"word": "aware", "translation": "осведомленный", "levels": ["B1"]},
    {"word": "benefit", "translation": "выгода", "levels": ["B1"]},
    {"word": "bother", "translation": "беспокоить", "levels": ["B1"]},
    {"word": "challenge", "translation": "вызов", "levels": ["B1"]},
    {"word": "chance", "translation": "шанс", "levels": ["B1"]},
    {"word": "character", "translation": "характер", "levels": ["B1"]},
    {"word": "claim", "translation": "утверждать", "levels": ["B1"]},
    {"word": "comfortable", "translation": "удобный", "levels": ["B1"]},
    {"word": "common", "translation": "общий", "levels": ["B1"]},
    {"word": "complain", "translation": "жаловаться", "levels": ["B1"]},
    {"word": "concern", "translation": "беспокойство", "levels": ["B1"]},
    {"word": "confident", "translation": "уверенный", "levels": ["B1"]},
    {"word": "consequence", "translation": "последствие", "levels": ["B1"]},
    {"word": "consider", "translation": "рассматривать", "levels": ["B1"]},
    {"word": "contribute", "translation": "вносить вклад", "levels": ["B1"]},
    {"word": "convenient", "translation": "удобный", "levels": ["B1"]},
    {"word": "curious", "translation": "любопытный", "levels": ["B1"]},
    {"word": "debate", "translation": "дебаты", "levels": ["B1"]},
    {"word": "decline", "translation": "снижение", "levels": ["B1"]},
    {"word": "decoration", "translation": "украшение", "levels": ["B1"]},
    {"word": "delight", "translation": "удовольствие", "levels": ["B1"]},
    {"word": "demand", "translation": "спрос", "levels": ["B1"]},
    {"word": "deny", "translation": "отрицать", "levels": ["B1"]},
    {"word": "deserve", "translation": "заслуживать", "levels": ["B1"]},
    {"word": "determined", "translation": "решительный", "levels": ["B1"]},
    {"word": "develop", "translation": "развивать", "levels": ["B1"]},
    {"word": "disappoint", "translation": "разочаровывать", "levels": ["B1"]},
    {"word": "discovery", "translation": "открытие", "levels": ["B1"]},
    {"word": "display", "translation": "показ", "levels": ["B1"]},
    {"word": "disturb", "translation": "беспокоить", "levels": ["B1"]},
    {"word": "doubt", "translation": "сомневаться", "levels": ["B1"]},
    {"word": "effect", "translation": "эффект", "levels": ["B1"]},
    {"word": "efficient", "translation": "эффективный", "levels": ["B1"]},
    {"word": "emphasis", "translation": "акцент", "levels": ["B1"]},
    {"word": "encourage", "translation": "поощрять", "levels": ["B1"]},
    {"word": "engage", "translation": "вовлекать", "levels": ["B1"]},
    {"word": "enjoyable", "translation": "приятный", "levels": ["B1"]},
    {"word": "entertain", "translation": "развлекать", "levels": ["B1"]},
    {"word": "enthusiasm", "translation": "энтузиазм", "levels": ["B1"]},
    {"word": "environment", "translation": "окружающая среда", "levels": ["B1"]},
    {"word": "essential", "translation": "существенный", "levels": ["B1"]},
    {"word": "establish", "translation": "устанавливать", "levels": ["B1"]},
    {"word": "evidence", "translation": "доказательство", "levels": ["B1"]},
    {"word": "exchange", "translation": "обмен", "levels": ["B1"]},
    {"word": "expectation", "translation": "ожидание", "levels": ["B1"]},
    {"word": "explanation", "translation": "объяснение", "levels": ["B1"]},
    {"word": "explore", "translation": "исследовать", "levels": ["B1"]},
    {"word": "familiar", "translation": "знакомый", "levels": ["B1"]},
    {"word": "fascinating", "translation": "увлекательный", "levels": ["B1"]},
    {"word": "financial", "translation": "финансовый", "levels": ["B1"]},
    {"word": "focus", "translation": "фокусироваться", "levels": ["B1"]},
    {"word": "fortunate", "translation": "счастливый", "levels": ["B1"]},
    {"word": "freedom", "translation": "свобода", "levels": ["B1"]},
    {"word": "function", "translation": "функция", "levels": ["B1"]},
    {"word": "generation", "translation": "поколение", "levels": ["B1"]},
    {"word": "genuine", "translation": "подлинный", "levels": ["B1"]},
    {"word": "goal", "translation": "цель", "levels": ["B1"]},
    {"word": "guilty", "translation": "виновный", "levels": ["B1"]},
    {"word": "handle", "translation": "управлять", "levels": ["B1"]},
    {"word": "harmful", "translation": "вредный", "levels": ["B1"]},
    {"word": "hesitate", "translation": "колебаться", "levels": ["B1"]},
    {"word": "identity", "translation": "личность", "levels": ["B1"]},
    {"word": "ignore", "translation": "игнорировать", "levels": ["B1"]},
    {"word": "imagine", "translation": "представлять", "levels": ["B1"]},
    {"word": "impressive", "translation": "впечатляющий", "levels": ["B1"]},
    {"word": "include", "translation": "включать", "levels": ["B1"]},
    {"word": "independent", "translation": "независимый", "levels": ["B1"]},
    {"word": "influence", "translation": "влияние", "levels": ["B1"]},
    {"word": "abandon", "translation": "оставлять", "levels": ["B2"]},
    {"word": "abstract", "translation": "абстрактный", "levels": ["B2"]},
    {"word": "accompany", "translation": "сопровождать", "levels": ["B2"]},
    {"word": "acquire", "translation": "приобретать", "levels": ["B2"]},
    {"word": "adapt", "translation": "адаптировать", "levels": ["B2"]},
    {"word": "adequate", "translation": "адекватный", "levels": ["B2"]},
    {"word": "advocate", "translation": "защищать", "levels": ["B2"]},
    {"word": "alternative", "translation": "альтернатива", "levels": ["B2"]},
    {"word": "analyze", "translation": "анализировать", "levels": ["B2"]},
    {"word": "anticipate", "translation": "предвидеть", "levels": ["B2"]},
    {"word": "apparent", "translation": "очевидный", "levels": ["B2"]},
    {"word": "appreciation", "translation": "признательность", "levels": ["B2"]},
    {"word": "appropriate", "translation": "соответствующий", "levels": ["B2"]},
    {"word": "assess", "translation": "оценивать", "levels": ["B2"]},
    {"word": "assume", "translation": "предполагать", "levels": ["B2"]},
    {"word": "assure", "translation": "уверять", "levels": ["B2"]},
    {"word": "attempt", "translation": "попытка", "levels": ["B2"]},
    {"word": "attribute", "translation": "атрибут", "levels": ["B2"]},
    {"word": "automatic", "translation": "автоматический", "levels": ["B2"]},
    {"word": "barrier", "translation": "барьер", "levels": ["B2"]},
    {"word": "capable", "translation": "способный", "levels": ["B2"]},
    {"word": "clarify", "translation": "уточнять", "levels": ["B2"]},
    {"word": "collapse", "translation": "разрушаться", "levels": ["B2"]},
    {"word": "compensate", "translation": "компенсировать", "levels": ["B2"]},
    {"word": "comply", "translation": "соблюдать", "levels": ["B2"]},
    {"word": "compose", "translation": "сочинять", "levels": ["B2"]},
    {"word": "conceive", "translation": "задумать", "levels": ["B2"]},
    {"word": "conclude", "translation": "делать вывод", "levels": ["B2"]},
    {"word": "confront", "translation": "противостоять", "levels": ["B2"]},
    {"word": "conscious", "translation": "осознанный", "levels": ["B2"]},
    {"word": "consist", "translation": "состоять", "levels": ["B2"]},
    {"word": "constraint", "translation": "ограничение", "levels": ["B2"]},
    {"word": "consult", "translation": "консультироваться", "levels": ["B2"]},
    {"word": "controversy", "translation": "спор", "levels": ["B2"]},
    {"word": "convention", "translation": "соглашение", "levels": ["B2"]},
    {"word": "convince", "translation": "убеждать", "levels": ["B2"]},
    {"word": "coordinate", "translation": "координировать", "levels": ["B2"]},
    {"word": "crucial", "translation": "решающий", "levels": ["B2"]},
    {"word": "derive", "translation": "получать", "levels": ["B2"]},
    {"word": "devote", "translation": "посвящать", "levels": ["B2"]},
    {"word": "discriminate", "translation": "дискриминировать", "levels": ["B2"]},
    {"word": "distinction", "translation": "различие", "levels": ["B2"]},
    {"word": "diverse", "translation": "разнообразный", "levels": ["B2"]},
    {"word": "domain", "translation": "область", "levels": ["B2"]},
    {"word": "dominate", "translation": "доминировать", "levels": ["B2"]},
    {"word": "elaborate", "translation": "разрабатывать", "levels": ["B2"]},
    {"word": "emphasize", "translation": "подчеркивать", "levels": ["B2"]},
    {"word": "ensure", "translation": "обеспечивать", "levels": ["B2"]},
    {"word": "equivalent", "translation": "эквивалент", "levels": ["B2"]},
    {"word": "estimate", "translation": "оценивать", "levels": ["B2"]},
    {"word": "evaluate", "translation": "оценивать", "levels": ["B2"]},
    {"word": "evolve", "translation": "развиваться", "levels": ["B2"]},
    {"word": "exceed", "translation": "превышать", "levels": ["B2"]},
    {"word": "expertise", "translation": "экспертиза", "levels": ["B2"]},
    {"word": "explicit", "translation": "явный", "levels": ["B2"]},
    {"word": "external", "translation": "внешний", "levels": ["B2"]},
    {"word": "facilitate", "translation": "содействовать", "levels": ["B2"]},
    {"word": "feasible", "translation": "осуществимый", "levels": ["B2"]},
    {"word": "flexible", "translation": "гибкий", "levels": ["B2"]},
    {"word": "foundation", "translation": "основа", "levels": ["B2"]},
    {"word": "framework", "translation": "рамки", "levels": ["B2"]},
    {"word": "generate", "translation": "генерировать", "levels": ["B2"]},
    {"word": "guarantee", "translation": "гарантия", "levels": ["B2"]},
    {"word": "hypothesis", "translation": "гипотеза", "levels": ["B2"]},
    {"word": "illustrate", "translation": "иллюстрировать", "levels": ["B2"]},
    {"word": "implement", "translation": "осуществлять", "levels": ["B2"]},
    {"word": "implication", "translation": "последствие", "levels": ["B2"]},
    {"word": "imply", "translation": "подразумевать", "levels": ["B2"]},
    {"word": "inevitable", "translation": "неизбежный", "levels": ["B2"]},
    {"word": "influence", "translation": "влияние", "levels": ["B2"]},
    {"word": "infrastructure", "translation": "инфраструктура", "levels": ["B2"]},
    {"word": "inherent", "translation": "присущий", "levels": ["B2"]},
    {"word": "initiative", "translation": "инициатива", "levels": ["B2"]},
    {"word": "integrate", "translation": "интегрировать", "levels": ["B2"]},
    {"word": "interpret", "translation": "интерпретировать", "levels": ["B2"]},
    {"word": "intervene", "translation": "вмешиваться", "levels": ["B2"]},
    {"word": "intrinsic", "translation": "внутренний", "levels": ["B2"]},
    {"word": "abundant", "translation": "обильный", "levels": ["C1"]},
    {"word": "acquisition", "translation": "приобретение", "levels": ["C1"]},
    {"word": "allegation", "translation": "обвинение", "levels": ["C1"]},
    {"word": "ambiguous", "translation": "двусмысленный", "levels": ["C1"]},
    {"word": "analogy", "translation": "аналогия", "levels": ["C1"]},
    {"word": "anecdotal", "translation": "анекдотический", "levels": ["C1"]},
    {"word": "antagonistic", "translation": "враждебный", "levels": ["C1"]},
    {"word": "arbitrary", "translation": "произвольный", "levels": ["C1"]},
    {"word": "articulate", "translation": "ясно выражающий свои мысли", "levels": ["C1"]},
    {"word": "assertion", "translation": "утверждение", "levels": ["C1"]},
    {"word": "assumption", "translation": "предположение", "levels": ["C1"]},
    {"word": "astonishing", "translation": "поразительный", "levels": ["C1"]},
    {"word": "attribute", "translation": "приписывать", "levels": ["C1"]},
    {"word": "authenticity", "translation": "подлинность", "levels": ["C1"]},
    {"word": "autonomy", "translation": "автономия", "levels": ["C1"]},
    {"word": "benchmark", "translation": "эталон", "levels": ["C1"]},
    {"word": "brevity", "translation": "краткость", "levels": ["C1"]},
    {"word": "chronology", "translation": "хронология", "levels": ["C1"]},
    {"word": "coherent", "translation": "согласованный", "levels": ["C1"]},
    {"word": "collaboration", "translation": "сотрудничество", "levels": ["C1"]},
    {"word": "commence", "translation": "начинать", "levels": ["C1"]},
    {"word": "compilation", "translation": "сборник", "levels": ["C1"]},
    {"word": "complementary", "translation": "дополняющий", "levels": ["C1"]},
    {"word": "comprehensive", "translation": "всесторонний", "levels": ["C1"]},
    {"word": "compromise", "translation": "компромисс", "levels": ["C1"]},
    {"word": "conception", "translation": "зачатие", "levels": ["C1"]},
    {"word": "concurrent", "translation": "одновременный", "levels": ["C1"]},
    {"word": "connotation", "translation": "подтекст", "levels": ["C1"]},
    {"word": "constituent", "translation": "составной элемент", "levels": ["C1"]},
    {"word": "contemplate", "translation": "созерцать", "levels": ["C1"]},
    {"word": "contemporary", "translation": "современный", "levels": ["C1"]},
    {"word": "contingency", "translation": "непредвиденное обстоятельство", "levels": ["C1"]},
    {"word": "contradict", "translation": "противоречить", "levels": ["C1"]},
    {"word": "correlation", "translation": "корреляция", "levels": ["C1"]},
    {"word": "credibility", "translation": "достоверность", "levels": ["C1"]},
    {"word": "criterion", "translation": "критерий", "levels": ["C1"]},
    {"word": "culmination", "translation": "кульминация", "levels": ["C1"]},
    {"word": "cynical", "translation": "циничный", "levels": ["C1"]},
    {"word": "deduction", "translation": "вывод", "levels": ["C1"]},
    {"word": "degradation", "translation": "деградация", "levels": ["C1"]},
    {"word": "deviation", "translation": "отклонение", "levels": ["C1"]},
    {"word": "dilemma", "translation": "дилемма", "levels": ["C1"]},
    {"word": "discrepancy", "translation": "несоответствие", "levels": ["C1"]},
    {"word": "dispersion", "translation": "рассеивание", "levels": ["C1"]},
    {"word": "dissonance", "translation": "диссонанс", "levels": ["C1"]},
    {"word": "distort", "translation": "искажать", "levels": ["C1"]},
    {"word": "elucidate", "translation": "разъяснять", "levels": ["C1"]},
    {"word": "empirical", "translation": "эмпирический", "levels": ["C1"]},
    {"word": "epitome", "translation": "воплощение", "levels": ["C1"]},
    {"word": "aberration", "translation": "отклонение от нормы", "levels": ["C2"]},
    {"word": "acumen", "translation": "проницательность", "levels": ["C2"]},
    {"word": "anathema", "translation": "анафема", "levels": ["C2"]},
    {"word": "ascertain", "translation": "устанавливать", "levels": ["C2"]},
    {"word": "assiduous", "translation": "усердный", "levels": ["C2"]},
    {"word": "beleaguered", "translation": "осажденный", "levels": ["C2"]},
    {"word": "capitulate", "translation": "капитулировать", "levels": ["C2"]},
    {"word": "chicanery", "translation": "уловка", "levels": ["C2"]},
    {"word": "cognizant", "translation": "осведомленный", "levels": ["C2"]},
    {"word": "connive", "translation": "потворствовать", "levels": ["C2"]},
    {"word": "connoisseur", "translation": "знаток", "levels": ["C2"]},
    {"word": "debilitate", "translation": "ослаблять", "levels": ["C2"]},
    {"word": "deleterious", "translation": "вредный", "levels": ["C2"]},
    {"word": "disparage", "translation": "унижать", "levels": ["C2"]},
    {"word": "egregious", "translation": "вопиющий", "levels": ["C2"]},
    {"word": "enervate", "translation": "обессиливать", "levels": ["C2"]},
    {"word": "ephemeral", "translation": "эфемерный", "levels": ["C2"]},
    {"word": "equivocate", "translation": "увиливать", "levels": ["C2"]},
    {"word": "extol", "translation": "превозносить", "levels": ["C2"]},
    {"word": "fastidious", "translation": "привередливый", "levels": ["C2"]},
    {"word": "intransigent", "translation": "непримиримый", "levels": ["C2"]},
    {"word": "mendacious", "translation": "лживый", "levels": ["C2"]},
    {"word": "nonplussed", "translation": "озадаченный", "levels": ["C2"]},
    {"word": "obfuscate", "translation": "затемнять", "levels": ["C2"]},
    {"word": "recalcitrant", "translation": "непокорный", "levels": ["C2"]},
    {"word": "one", "translation": "1", "levels": ["number"]},
    {"word": "two", "translation": "2", "levels": ["number"]},
    {"word": "three", "translation": "3", "levels": ["number"]},
    {"word": "four", "translation": "4", "levels": ["number"]},
    {"word": "five", "translation": "5", "levels": ["number"]},
    {"word": "six", "translation": "6", "levels": ["number"]},
    {"word": "seven", "translation": "7", "levels": ["number"]},
    {"word": "eight", "translation": "8", "levels": ["number"]},
    {"word": "nine", "translation": "9", "levels": ["number"]},
    {"word": "ten", "translation": "10", "levels": ["number"]},
    {"word": "eleven", "translation": "11", "levels": ["number"]},
    {"word": "twelve", "translation": "12", "levels": ["number"]},
    {"word": "thirteen", "translation": "13", "levels": ["number"]},
    {"word": "fourteen", "translation": "14", "levels": ["number"]},
    {"word": "fifteen", "translation": "15", "levels": ["number"]},
    {"word": "sixteen", "translation": "16", "levels": ["number"]},
    {"word": "seventeen", "translation": "17", "levels": ["number"]},
    {"word": "eighteen", "translation": "18", "levels": ["number"]},
    {"word": "nineteen", "translation": "19", "levels": ["number"]},
    {"word": "twenty", "translation": "20", "levels": ["number"]},
    {"word": "thirty", "translation": "30", "levels": ["number"]},
    {"word": "forty", "translation": "40", "levels": ["number"]},
    {"word": "fifty", "translation": "50", "levels": ["number"]},
    {"word": "sixty", "translation": "60", "levels": ["number"]},
    {"word": "seventy", "translation": "70", "levels": ["number"]},
    {"word": "eighty", "translation": "80", "levels": ["number"]},
    {"word": "ninety", "translation": "90", "levels": ["number"]},
    {"word": "one hundred", "translation": "100", "levels": ["number"]},
    {"word": "one thousand", "translation": "1000", "levels": ["number"]},
    {"word": "money", "translation": "деньги", "levels": ["required-100"]},
    {"word": "time", "translation": "время", "levels": ["required-100"]},
    {"word": "friend", "translation": "друг", "levels": ["required-100"]},
    {"word": "family", "translation": "семья", "levels": ["required-100"]},
    {"word": "love", "translation": "любовь", "levels": ["required-100"]},
    {"word": "city", "translation": "город", "levels": ["required-100"]},
    {"word": "country", "translation": "страна", "levels": ["required-100"]},
    {"word": "day", "translation": "день", "levels": ["required-100"]},
    {"word": "week", "translation": "неделя", "levels": ["required-100"]},
    {"word": "month", "translation": "месяц", "levels": ["required-100"]},
    {"word": "year", "translation": "год", "levels": ["required-100"]},
    {"word": "weather", "translation": "погода", "levels": ["required-100"]},
    {"word": "snow", "translation": "снег", "levels": ["required-100"]},
    {"word": "child", "translation": "ребенок", "levels": ["required-100"]},
    {"word": "woman", "translation": "женщина", "levels": ["required-100"]},
    {"word": "brother", "translation": "брат", "levels": ["required-100"]},
    {"word": "sister", "translation": "сестра", "levels": ["required-100"]},
    {"word": "mother", "translation": "мать", "levels": ["required-100"]},
    {"word": "father", "translation": "отец", "levels": ["required-100"]},
    {"word": "teacher", "translation": "учитель", "levels": ["required-100"]},
    {"word": "student", "translation": "студент", "levels": ["required-100"]},
    {"word": "friendship", "translation": "дружба", "levels": ["required-100"]},
    {"word": "problem", "translation": "проблема", "levels": ["required-100"]},
    {"word": "solution", "translation": "решение", "levels": ["required-100"]},
    {"word": "question", "translation": "вопрос", "levels": ["required-100"]},
    {"word": "answer", "translation": "ответ", "levels": ["required-100"]},
    {"word": "chair", "translation": "стул", "levels": ["required-100"]},
    {"word": "bed", "translation": "кровать", "levels": ["required-100"]},
    {"word": "phone", "translation": "телефон", "levels": ["required-100"]},
    {"word": "computer", "translation": "компьютер", "levels": ["required-100"]},
    {"word": "internet", "translation": "интернет", "levels": ["required-100"]},
    {"word": "music", "translation": "музыка", "levels": ["required-100"]},
    {"word": "book", "translation": "книга", "levels": ["required-100"]},
    {"word": "newspaper", "translation": "газета", "levels": ["required-100"]},
    {"word": "magazine", "translation": "журнал", "levels": ["required-100"]},
    {"word": "movie", "translation": "фильм", "levels": ["required-100"]},
    {"word": "game", "translation": "игра", "levels": ["required-100"]},
    {"word": "sport", "translation": "спорт", "levels": ["required-100"]},
    {"word": "ball", "translation": "мяч", "levels": ["required-100"]},
    {"word": "shoe", "translation": "обувь", "levels": ["required-100"]},
    {"word": "clothes", "translation": "одежда", "levels": ["required-100"]},
    {"word": "shirt", "translation": "рубашка", "levels": ["required-100"]},
    {"word": "pants", "translation": "штаны", "levels": ["required-100"]},
    {"word": "hat", "translation": "шляпа", "levels": ["required-100"]},
    {"word": "jacket", "translation": "куртка", "levels": ["required-100"]},
    {"word": "coat", "translation": "пальто", "levels": ["required-100"]},
    {"word": "market", "translation": "рынок", "levels": ["required-100"]},
    {"word": "store", "translation": "магазин", "levels": ["required-100"]},
    {"word": "shop", "translation": "магазин", "levels": ["required-100"]},
    {"word": "bus", "translation": "автобус", "levels": ["required-100"]},
    {"word": "train", "translation": "поезд", "levels": ["required-100"]},
    {"word": "plane", "translation": "самолет", "levels": ["required-100"]},
    {"word": "ship", "translation": "корабль", "levels": ["required-100"]},
    {"word": "road", "translation": "дорога", "levels": ["required-100"]},
    {"word": "street", "translation": "улица", "levels": ["required-100"]},
    {"word": "bridge", "translation": "мост", "levels": ["required-100"]},
    {"word": "river", "translation": "река", "levels": ["required-100"]},
    {"word": "mountain", "translation": "гора", "levels": ["required-100"]},
    {"word": "beach", "translation": "пляж", "levels": ["required-100"]},
    {"word": "forest", "translation": "лес", "levels": ["required-100"]},
    {"word": "tree", "translation": "дерево", "levels": ["required-100"]},
    {"word": "flower", "translation": "цветок", "levels": ["required-100"]},
    {"word": "grass", "translation": "трава", "levels": ["required-100"]},
    {"word": "animal", "translation": "животное", "levels": ["required-100"]},
    {"word": "dog", "translation": "собака", "levels": ["required-100"]},
    {"word": "cat", "translation": "кот", "levels": ["required-100"]},
    {"word": "bird", "translation": "птица", "levels": ["required-100"]},
    {"word": "fish", "translation": "рыба", "levels": ["required-100"]},
    {"word": "food", "translation": "еда", "levels": ["required-100"]},
    {"word": "fruit", "translation": "фрукт", "levels": ["required-100"]},
    {"word": "vegetable", "translation": "овощ", "levels": ["required-100"]},
    {"word": "meat", "translation": "мясо", "levels": ["required-100"]},
    {"word": "bread", "translation": "хлеб", "levels": ["required-100"]},
    {"word": "butter", "translation": "масло", "levels": ["required-100"]},
    {"word": "cheese", "translation": "сыр", "levels": ["required-100"]},
    {"word": "milk", "translation": "молоко", "levels": ["required-100"]}
];